import type { Part, Profile, Template } from '../types';

const materials: Profile['materials'] = [
  {
    id: 'fabric',
    name: 'Fabric',
    category: 'fabric',
    role: 'stock',
    measure: 'area' as const,
    costPerUnit: 12.0,
    unitLabel: 'm2',
    color: '#d98ba6',
  },
  {
    id: 'denim',
    name: 'Denim',
    category: 'fabric',
    role: 'stock',
    measure: 'area' as const,
    costPerUnit: 14.0,
    unitLabel: 'm2',
    color: '#5a6a8a',
  },
  {
    id: 'lining',
    name: 'Lining fabric',
    category: 'fabric',
    role: 'stock',
    measure: 'area' as const,
    costPerUnit: 8.0,
    unitLabel: 'm2',
    color: '#b0b7c4',
  },
  {
    id: 'interfacing',
    name: 'Interfacing',
    category: 'fabric',
    role: 'stock',
    measure: 'area' as const,
    costPerUnit: 6.0,
    unitLabel: 'm2',
    color: '#d8d2c4',
  },
  {
    id: 'thread',
    name: 'Thread',
    category: 'notions',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 2.5,
    unitLabel: 'spool',
    color: '#e7d06b',
  },
  {
    id: 'button',
    name: 'Buttons',
    category: 'notions',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 0.4,
    unitLabel: 'pc',
    color: '#a8522f',
  },
  {
    id: 'zipper',
    name: 'Zips',
    category: 'notions',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 1.8,
    unitLabel: 'pc',
    color: '#8d939b',
  },
  {
    id: 'elastic',
    name: 'Elastic',
    category: 'bands',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 1.1,
    unitLabel: 'm',
    color: '#cfd0d6',
  },
  {
    id: 'ribbon',
    name: 'Ribbon / tape',
    category: 'bands',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 1.5,
    unitLabel: 'm',
    color: '#d9a7c4',
  },
  {
    id: 'lace',
    name: 'Lace trim',
    category: 'decor',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 2.8,
    unitLabel: 'm',
    color: '#efe6da',
  },
  {
    id: 'sequin',
    name: 'Sequins',
    category: 'decor',
    role: 'stock',
    measure: 'count' as const,
    costPerUnit: 3.0,
    unitLabel: 'pack',
    color: '#c2b8e0',
  },
  {
    id: 'hookloop',
    name: 'Hook-and-loop tape',
    category: 'notions',
    role: 'fixing',
    measure: 'linear' as const,
    costPerUnit: 2.2,
    unitLabel: 'm',
    color: '#a9aeb6',
  },
];

const partKinds: Profile['partKinds'] = [
  {
    id: 'pattern',
    label: 'Pattern piece',
    defaultMaterialId: 'fabric',
    defaultLength: 600,
    defaultWidth: 600,
    defaultThickness: 0,
    measure: 'area' as const,
  },
  {
    id: 'band',
    label: 'Band / strap',
    defaultMaterialId: 'elastic',
    defaultLength: 800,
    defaultWidth: 60,
    defaultThickness: 0,
    defaultShape: 'line',
    measure: 'linear' as const,
  },
  {
    id: 'pocket',
    label: 'Pocket',
    defaultMaterialId: 'fabric',
    defaultLength: 200,
    defaultWidth: 200,
    defaultThickness: 0,
    measure: 'area' as const,
  },
  {
    id: 'trim',
    label: 'Trim',
    defaultMaterialId: 'elastic',
    defaultLength: 500,
    defaultWidth: 20,
    defaultThickness: 0,
    defaultShape: 'line',
    measure: 'linear' as const,
  },
];

function part(
  kindId: string,
  materialId: string,
  label: string,
  x: number,
  y: number,
  sizeX: number,
  sizeY: number,
  quantity: number,
  dimensions: { length: number; width: number; thickness: number },
): Omit<Part, 'id'> {
  return {
    kindId,
    materialId,
    label,
    position: { x, y },
    size: { x: sizeX, y: sizeY },
    rotation: 0,
    quantity,
    dimensions,
  };
}

const apronParts: Omit<Part, 'id'>[] = [
  part('pattern', 'fabric', 'Apron main', 0, 0, 800, 600, 1, { length: 800, width: 600, thickness: 0 }),
  part('pocket', 'fabric', 'Pocket', 100, 640, 200, 180, 1, { length: 200, width: 180, thickness: 0 }),
  part('band', 'elastic', 'Waist band', 0, 860, 900, 60, 1, { length: 900, width: 60, thickness: 0 }),
  part('band', 'elastic', 'Strap', 0, 960, 100, 500, 2, { length: 500, width: 60, thickness: 0 }),
  part('trim', 'fabric', 'Trim', 0, 1100, 400, 20, 1, { length: 400, width: 20, thickness: 0 }),
  part('pocket', 'button', 'Buttons', 500, 640, 40, 40, 4, { length: 40, width: 40, thickness: 5 }),
  part('pattern', 'thread', 'Thread', 600, 640, 80, 40, 1, { length: 80, width: 40, thickness: 40 }),
];

const templates: Template[] = [
  { id: 'apron', name: 'Apron', parts: apronParts },
];

export const clothes: Profile = {
  id: 'clothes',
  name: 'Clothes',
  color: '#d96a9a',
  displayUnit: 'cm',
  precision: 1,
  gridSize: 10,
  snap: true,
  materials,
  partKinds,
  templates,
};