import type { Part, Profile, Template } from '../types';

const materials: Profile['materials'] = [
  {
    id: 'timber-50x100',
    name: 'Timber 50 x 100',
    category: 'timber',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 6.5,
    unitLabel: 'm',
    color: '#cfb27a',
    stock: [{ length: 3600 }, { length: 4800 }],
  },
  {
    id: 'timber-50x150',
    name: 'Timber 50 x 150',
    category: 'timber',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 9.0,
    unitLabel: 'm',
    color: '#bfa066',
    stock: [{ length: 3600 }, { length: 4800 }],
  },
  {
    id: 'decking-25x100',
    name: 'Decking board 25 x 100',
    category: 'timber',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 5.0,
    unitLabel: 'm',
    color: '#b8945f',
    stock: [{ length: 3600 }],
  },
  {
    id: 'plywood-18',
    name: 'Plywood 18 mm',
    category: 'boards',
    role: 'stock',
    measure: 'area' as const,
    costPerUnit: 24.0,
    unitLabel: 'm2',
    color: '#e3cfa5',
    stock: [{ length: 2440, width: 1220 }],
  },
  {
    id: 'osb-18',
    name: 'OSB 18 mm',
    category: 'boards',
    role: 'stock',
    measure: 'area' as const,
    costPerUnit: 12.0,
    unitLabel: 'm2',
    color: '#d8c48f',
    stock: [{ length: 2440, width: 1220 }],
  },
  {
    id: 'board-panel',
    name: 'Board panel',
    category: 'panels',
    role: 'stock',
    measure: 'area' as const,
    costPerUnit: 18.0,
    unitLabel: 'm2',
    color: '#e8ddc4',
  },
  {
    id: 'concrete-bag',
    name: 'Ready-mix concrete 25 kg',
    category: 'concrete',
    role: 'stock',
    measure: 'count' as const,
    costPerUnit: 6.5,
    unitLabel: 'bag',
    color: '#a9a29a',
  },
  {
    id: 'gravel',
    name: 'Gravel',
    category: 'concrete',
    role: 'stock',
    measure: 'count' as const,
    costPerUnit: 4.0,
    unitLabel: 'bag',
    color: '#b0aca4',
  },
  {
    id: 'sand',
    name: 'Sharp sand',
    category: 'concrete',
    role: 'stock',
    measure: 'count' as const,
    costPerUnit: 3.5,
    unitLabel: 'bag',
    color: '#c9b58f',
  },
  {
    id: 'screw-60',
    name: 'Deck screw 60 mm',
    category: 'fasteners',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 0.1,
    unitLabel: 'pc',
    color: '#9aa0aa',
  },
  {
    id: 'nail-90',
    name: 'Galvanised nail 90 mm',
    category: 'fasteners',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 0.05,
    unitLabel: 'pc',
    color: '#8b95a1',
  },
  {
    id: 'bolt-m10',
    name: 'Bolt / post anchor',
    category: 'fasteners',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 0.6,
    unitLabel: 'pc',
    color: '#78808c',
  },
];

const partKinds: Profile['partKinds'] = [
  {
    id: 'timber',
    label: 'Timber',
    defaultMaterialId: 'timber-50x100',
    defaultLength: 2400,
    defaultWidth: 100,
    defaultThickness: 50,
    defaultShape: 'line',
    measure: 'linear' as const,
  },
  {
    id: 'board',
    label: 'Board / ply',
    defaultMaterialId: 'plywood-18',
    defaultLength: 800,
    defaultWidth: 800,
    defaultThickness: 18,
    measure: 'area' as const,
  },
  {
    id: 'footing',
    label: 'Footing / concrete',
    defaultMaterialId: 'concrete-bag',
    defaultLength: 300,
    defaultWidth: 300,
    defaultThickness: 100,
    measure: 'count' as const,
  },
  {
    id: 'fastener',
    label: 'Fastener',
    defaultMaterialId: 'screw-60',
    defaultLength: 120,
    defaultWidth: 60,
    defaultThickness: 6,
    defaultShape: 'circle',
    measure: 'count' as const,
  },
];

function part(
  kindId: string,
  materialId: string,
  label: string,
  x: number,
  y: number,
  sizeX: number,
  sizeY: number,
  quantity: number,
  dimensions: { length: number; width: number; thickness: number },
): Omit<Part, 'id'> {
  return {
    kindId,
    materialId,
    label,
    position: { x, y },
    size: { x: sizeX, y: sizeY },
    rotation: 0,
    quantity,
    dimensions,
  };
}

const deckParts: Omit<Part, 'id'>[] = [
  part('timber', 'timber-50x100', 'Joist', 0, 0, 2400, 100, 4, { length: 2400, width: 100, thickness: 50 }),
  part('timber', 'decking-25x100', 'Decking board', 0, 500, 2400, 100, 6, { length: 2400, width: 100, thickness: 25 }),
  part('footing', 'concrete-bag', 'Concrete footing', 0, 1200, 300, 300, 4, { length: 300, width: 300, thickness: 100 }),
  part('fastener', 'screw-60', 'Deck screws', 400, 1200, 120, 60, 100, { length: 120, width: 60, thickness: 6 }),
  part('fastener', 'bolt-m10', 'Post anchors', 600, 1200, 120, 60, 8, { length: 120, width: 60, thickness: 6 }),
];

const fenceParts: Omit<Part, 'id'>[] = [
  part('timber', 'timber-50x100', 'Fence post', 0, 0, 100, 1800, 3, { length: 1800, width: 100, thickness: 50 }),
  part('timber', 'decking-25x100', 'Picket', 300, 0, 100, 900, 8, { length: 900, width: 100, thickness: 25 }),
  part('footing', 'concrete-bag', 'Concrete for posts', 0, 1000, 300, 300, 3, { length: 300, width: 300, thickness: 100 }),
  part('fastener', 'screw-60', 'Screws', 500, 1000, 120, 60, 40, { length: 120, width: 60, thickness: 6 }),
];

const templates: Template[] = [
  { id: 'deck', name: 'Small deck', parts: deckParts },
  { id: 'fence', name: 'Fence panel', parts: fenceParts },
];

export const construction: Profile = {
  id: 'construction',
  name: 'Construction',
  color: '#4f7db0',
  displayUnit: 'mm',
  precision: 0,
  gridSize: 10,
  snap: true,
  materials,
  partKinds,
  templates,
};