import type { Part, Profile, Template } from '../types';

const materials: Profile['materials'] = [
  {
    id: 'cable-1.5',
    name: 'Twin & earth 1.5 mm2',
    category: 'cable',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 1.1,
    unitLabel: 'm',
    color: '#caa23a',
  },
  {
    id: 'cable-2.5',
    name: 'Twin & earth 2.5 mm2',
    category: 'cable',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 1.7,
    unitLabel: 'm',
    color: '#b8912f',
  },
  {
    id: 'cable-6',
    name: 'Twin & earth 6 mm2',
    category: 'cable',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 3.6,
    unitLabel: 'm',
    color: '#a07f28',
  },
  {
    id: 'conduit-20',
    name: 'Conduit 20 mm',
    category: 'containment',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 0.9,
    unitLabel: 'm',
    color: '#b0b7c4',
  },
  {
    id: 'trunking',
    name: 'Trunking',
    category: 'containment',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 2.2,
    unitLabel: 'm',
    color: '#d8d2c4',
  },
  {
    id: 'backbox',
    name: 'Back box',
    category: 'accessory',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 0.8,
    unitLabel: 'pc',
    color: '#8b95a1',
  },
  {
    id: 'socket',
    name: 'Double socket',
    category: 'accessory',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 7.5,
    unitLabel: 'pc',
    color: '#e6e9ee',
  },
  {
    id: 'switch',
    name: 'Light switch',
    category: 'accessory',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 4.0,
    unitLabel: 'pc',
    color: '#d7d8da',
  },
  {
    id: 'downlight',
    name: 'LED downlight',
    category: 'lighting',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 9.0,
    unitLabel: 'pc',
    color: '#f0f2f5',
  },
  {
    id: 'breaker',
    name: 'MCB',
    category: 'protection',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 6.0,
    unitLabel: 'pc',
    color: '#6b7280',
  },
  {
    id: 'gland',
    name: 'Cable gland',
    category: 'fixing',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 1.4,
    unitLabel: 'pc',
    color: '#9aa0aa',
  },
  {
    id: 'clip',
    name: 'Cable clip',
    category: 'fixing',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 0.06,
    unitLabel: 'pc',
    color: '#a8adb5',
  },
  {
    id: 'wago',
    name: 'Connector block',
    category: 'fixing',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 0.45,
    unitLabel: 'pc',
    color: '#e07b39',
  },
];

const partKinds: Profile['partKinds'] = [
  {
    id: 'cable',
    label: 'Cable run',
    defaultMaterialId: 'cable-1.5',
    defaultLength: 1000,
    defaultWidth: 8,
    defaultThickness: 3,
    defaultShape: 'line',
    measure: 'linear' as const,
  },
  {
    id: 'containment',
    label: 'Conduit / trunking',
    defaultMaterialId: 'conduit-20',
    defaultLength: 1000,
    defaultWidth: 20,
    defaultThickness: 20,
    defaultShape: 'line',
    measure: 'linear' as const,
  },
  {
    id: 'accessory',
    label: 'Accessory',
    defaultMaterialId: 'socket',
    defaultLength: 86,
    defaultWidth: 86,
    defaultThickness: 35,
    defaultShape: 'circle',
    measure: 'count' as const,
  },
  {
    id: 'lighting',
    label: 'Light fitting',
    defaultMaterialId: 'downlight',
    defaultLength: 90,
    defaultWidth: 90,
    defaultThickness: 40,
    defaultShape: 'circle',
    measure: 'count' as const,
  },
  {
    id: 'protection',
    label: 'Protection',
    defaultMaterialId: 'breaker',
    defaultLength: 18,
    defaultWidth: 80,
    defaultThickness: 70,
    measure: 'count' as const,
  },
];

function part(
  kindId: string,
  materialId: string,
  label: string,
  x: number,
  y: number,
  sizeX: number,
  sizeY: number,
  quantity: number,
  dimensions: { length: number; width: number; thickness: number },
): Omit<Part, 'id'> {
  return {
    kindId,
    materialId,
    label,
    position: { x, y },
    size: { x: sizeX, y: sizeY },
    rotation: 0,
    quantity,
    dimensions,
  };
}

const ringMainParts: Omit<Part, 'id'>[] = [
  part('cable', 'cable-2.5', 'Ring cable', 0, 0, 1000, 12, 24, { length: 1000, width: 12, thickness: 5 }),
  part('containment', 'conduit-20', 'Conduit', 0, 100, 1000, 20, 6, { length: 1000, width: 20, thickness: 20 }),
  part('accessory', 'backbox', 'Back box', 0, 200, 86, 86, 8, { length: 86, width: 86, thickness: 35 }),
  part('accessory', 'socket', 'Double socket', 100, 200, 86, 86, 8, { length: 86, width: 86, thickness: 35 }),
  part('protection', 'breaker', 'MCB', 200, 200, 18, 80, 1, { length: 18, width: 80, thickness: 70 }),
  part('accessory', 'wago', 'Connector block', 300, 200, 30, 20, 16, { length: 30, width: 20, thickness: 15 }),
  part('accessory', 'clip', 'Cable clips', 400, 200, 20, 20, 60, { length: 20, width: 20, thickness: 10 }),
];

const lightingCircuitParts: Omit<Part, 'id'>[] = [
  part('cable', 'cable-1.5', 'Lighting cable', 0, 0, 1000, 8, 18, { length: 1000, width: 8, thickness: 3 }),
  part('accessory', 'backbox', 'Switch box', 0, 100, 86, 86, 3, { length: 86, width: 86, thickness: 35 }),
  part('accessory', 'switch', 'Light switch', 100, 100, 86, 86, 3, { length: 86, width: 86, thickness: 35 }),
  part('lighting', 'downlight', 'Downlight', 200, 100, 90, 90, 6, { length: 90, width: 90, thickness: 40 }),
  part('protection', 'breaker', 'MCB', 300, 100, 18, 80, 1, { length: 18, width: 80, thickness: 70 }),
  part('accessory', 'wago', 'Connector block', 400, 100, 30, 20, 12, { length: 30, width: 20, thickness: 15 }),
];

const gardenPowerParts: Omit<Part, 'id'>[] = [
  part('cable', 'cable-6', 'Armoured feed', 0, 0, 1000, 16, 20, { length: 1000, width: 16, thickness: 16 }),
  part('containment', 'trunking', 'Trunking', 0, 100, 1000, 40, 8, { length: 1000, width: 40, thickness: 20 }),
  part('accessory', 'backbox', 'Back box', 0, 200, 86, 86, 2, { length: 86, width: 86, thickness: 35 }),
  part('accessory', 'socket', 'Socket', 100, 200, 86, 86, 2, { length: 86, width: 86, thickness: 35 }),
  part('protection', 'breaker', 'RCBO', 200, 200, 18, 80, 1, { length: 18, width: 80, thickness: 70 }),
  part('accessory', 'gland', 'Cable gland', 300, 200, 25, 25, 2, { length: 25, width: 25, thickness: 25 }),
  part('accessory', 'clip', 'Cable clips', 400, 200, 20, 20, 40, { length: 20, width: 20, thickness: 10 }),
];

const templates: Template[] = [
  { id: 'ring-main', name: 'Ring main', parts: ringMainParts },
  { id: 'lighting-circuit', name: 'Lighting circuit', parts: lightingCircuitParts },
  { id: 'garden-power', name: 'Garden power', parts: gardenPowerParts },
];

export const electrical: Profile = {
  id: 'electrical',
  name: 'Electrical',
  color: '#d8a13a',
  displayUnit: 'mm',
  precision: 0,
  gridSize: 5,
  snap: true,
  materials,
  partKinds,
  templates,
};
