import type { Part, Profile, Template } from '../types';

const materials: Profile['materials'] = [
  {
    id: 'timber-45x95',
    name: 'Pine timber 45 x 95',
    category: 'wood',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 9.5,
    unitLabel: 'm',
    color: '#d8b26a',
    supplier: 'Local yard',
  },
  {
    id: 'timber-45x145',
    name: 'Pine timber 45 x 145',
    category: 'wood',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 14.0,
    unitLabel: 'm',
    color: '#c99f57',
    supplier: 'Local yard',
  },
  {
    id: 'plywood-18',
    name: 'Plywood 18 mm',
    category: 'wood',
    role: 'stock',
    measure: 'area' as const,
    costPerUnit: 24.0,
    unitLabel: 'm2',
    color: '#e3cfa5',
    supplier: 'Local yard',
  },
  {
    id: 'mdf-18',
    name: 'MDF 18 mm',
    category: 'wood',
    role: 'stock',
    measure: 'area' as const,
    costPerUnit: 12.0,
    unitLabel: 'm2',
    color: '#d9cbb3',
    supplier: 'Local yard',
  },
  {
    id: 'hardwood-25',
    name: 'Hardwood board 25 mm',
    category: 'wood',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 24.0,
    unitLabel: 'm',
    color: '#a9703f',
  },
  {
    id: 'bolt-m8',
    name: 'Coach bolt M8 x 100',
    category: 'metal',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 0.75,
    unitLabel: 'pc',
    color: '#78808c',
  },
  {
    id: 'bracket-90',
    name: 'L-bracket 90 mm',
    category: 'metal',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 0.9,
    unitLabel: 'pc',
    color: '#8b95a1',
  },
  {
    id: 'hinge-50',
    name: 'Brass butt hinge',
    category: 'metal',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 3.2,
    unitLabel: 'pc',
    color: '#c2a24a',
  },
  {
    id: 'screw-70',
    name: 'Wood screw 70 mm',
    category: 'screws',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 0.12,
    unitLabel: 'pc',
    color: '#9aa0aa',
  },
  {
    id: 'screw-40',
    name: 'Wood screw 40 mm',
    category: 'screws',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 0.08,
    unitLabel: 'pc',
    color: '#a8adb5',
  },
  {
    id: 'decking-oil',
    name: 'Decking oil',
    category: 'paint',
    role: 'finish',
    measure: 'area' as const,
    costPerUnit: 9.0,
    unitLabel: 'm2',
    color: '#b7793f',
  },
  {
    id: 'wood-stain',
    name: 'Wood stain',
    category: 'paint',
    role: 'finish',
    measure: 'area' as const,
    costPerUnit: 7.5,
    unitLabel: 'm2',
    color: '#8a5a33',
  },
  {
    id: 'primer',
    name: 'Primer / sealer',
    category: 'paint',
    role: 'finish',
    measure: 'area' as const,
    costPerUnit: 6.0,
    unitLabel: 'm2',
    color: '#d7d2c8',
  },
];

const partKinds: Profile['partKinds'] = [
  {
    id: 'timber',
    label: 'Timber',
    defaultMaterialId: 'timber-45x95',
    defaultLength: 1200,
    defaultWidth: 95,
    defaultThickness: 45,
    defaultShape: 'line',
    measure: 'linear' as const,
  },
  {
    id: 'sheet',
    label: 'Panel',
    defaultMaterialId: 'plywood-18',
    defaultLength: 600,
    defaultWidth: 600,
    defaultThickness: 18,
    measure: 'area' as const,
  },
  {
    id: 'fastener',
    label: 'Fastener',
    defaultMaterialId: 'screw-70',
    defaultLength: 120,
    defaultWidth: 60,
    defaultThickness: 6,
    defaultShape: 'circle',
    measure: 'count' as const,
  },
  {
    id: 'finish',
    label: 'Finish',
    defaultMaterialId: 'decking-oil',
    defaultLength: 400,
    defaultWidth: 200,
    defaultThickness: 1,
    measure: 'area' as const,
  },
];

function timber(
  label: string,
  x: number,
  y: number,
  length: number,
  width: number,
  thickness: number,
  quantity: number,
  materialId = 'timber-45x95',
): Omit<Part, 'id'> {
  return {
    kindId: 'timber',
    materialId,
    label,
    position: { x, y },
    size: { x: length, y: width },
    rotation: 0,
    quantity,
    dimensions: { length, width, thickness },
  };
}

const benchParts: Omit<Part, 'id'>[] = [
  timber('Seat slat', 0, 0, 1500, 95, 45, 1),
  timber('Seat slat', 0, 105, 1500, 95, 45, 1),
  timber('Seat slat', 0, 210, 1500, 95, 45, 1),
  timber('Seat slat', 0, 315, 1500, 95, 45, 1),
  timber('Seat slat', 0, 420, 1500, 95, 45, 1),
  timber('Leg', 0, 560, 95, 450, 45, 4),
  timber('Stretcher', 95, 1030, 1310, 95, 45, 1),
  {
    kindId: 'fastener',
    materialId: 'screw-70',
    label: 'Wood screw 70 mm',
    position: { x: 0, y: 1160 },
    size: { x: 120, y: 60 },
    rotation: 0,
    quantity: 40,
    dimensions: { length: 120, width: 60, thickness: 6 },
  },
  {
    kindId: 'finish',
    materialId: 'decking-oil',
    label: 'Decking oil',
    position: { x: 200, y: 1160 },
    size: { x: 400, y: 120 },
    rotation: 0,
    quantity: 1,
    dimensions: { length: 1600, width: 600, thickness: 1 },
  },
];

const planterParts: Omit<Part, 'id'>[] = [
  timber('Long side', 0, 0, 900, 200, 45, 2),
  timber('Short side', 0, 220, 700, 200, 45, 2),
  {
    kindId: 'sheet',
    materialId: 'plywood-18',
    label: 'Base panel',
    position: { x: 0, y: 440 },
    size: { x: 800, y: 800 },
    rotation: 0,
    quantity: 1,
    dimensions: { length: 800, width: 800, thickness: 18 },
  },
  {
    kindId: 'fastener',
    materialId: 'screw-70',
    label: 'Wood screw 70 mm',
    position: { x: 840, y: 440 },
    size: { x: 120, y: 60 },
    rotation: 0,
    quantity: 24,
    dimensions: { length: 120, width: 60, thickness: 6 },
  },
];

const templates: Template[] = [
  { id: 'bench', name: 'Garden bench', parts: benchParts },
  { id: 'planter', name: 'Planter box', parts: planterParts },
];

export const furniture: Profile = {
  id: 'furniture',
  name: 'Furniture',
  color: '#b9823b',
  displayUnit: 'mm',
  precision: 0,
  gridSize: 10,
  snap: true,
  materials,
  partKinds,
  templates,
};