import type { Part, Profile, Template } from '../types';

const materials: Profile['materials'] = [
  {
    id: 'soil',
    name: 'Compost / soil',
    category: 'soil',
    role: 'stock',
    measure: 'count' as const,
    costPerUnit: 8.0,
    unitLabel: 'bag',
    color: '#7a5a3a',
  },
  {
    id: 'topsoil',
    name: 'Topsoil',
    category: 'soil',
    role: 'stock',
    measure: 'count' as const,
    costPerUnit: 5.5,
    unitLabel: 'bag',
    color: '#8a6b45',
  },
  {
    id: 'mulch',
    name: 'Mulch film / fleece',
    category: 'mulch',
    role: 'stock',
    measure: 'area' as const,
    costPerUnit: 1.2,
    unitLabel: 'm2',
    color: '#4a7d3f',
  },
  {
    id: 'bark',
    name: 'Bark chips',
    category: 'mulch',
    role: 'stock',
    measure: 'area' as const,
    costPerUnit: 2.0,
    unitLabel: 'm2',
    color: '#6b4a2e',
  },
  {
    id: 'plant',
    name: 'Young plant',
    category: 'plants',
    role: 'stock',
    measure: 'count' as const,
    costPerUnit: 2.5,
    unitLabel: 'pc',
    color: '#2f6d38',
  },
  {
    id: 'perennial',
    name: 'Perennial plant',
    category: 'plants',
    role: 'stock',
    measure: 'count' as const,
    costPerUnit: 6.0,
    unitLabel: 'pc',
    color: '#3a7d52',
  },
  {
    id: 'seed',
    name: 'Seed packet',
    category: 'seeds',
    role: 'stock',
    measure: 'count' as const,
    costPerUnit: 3.0,
    unitLabel: 'pk',
    color: '#c9a227',
  },
  {
    id: 'seedling',
    name: 'Seedling tray',
    category: 'seeds',
    role: 'stock',
    measure: 'count' as const,
    costPerUnit: 4.5,
    unitLabel: 'tray',
    color: '#b8a13f',
  },
  {
    id: 'fertilizer',
    name: 'Fertilizer',
    category: 'supplies',
    role: 'finish',
    measure: 'count' as const,
    costPerUnit: 12.0,
    unitLabel: 'bag',
    color: '#8a6d3b',
  },
  {
    id: 'pesticide',
    name: 'Plant protection',
    category: 'supplies',
    role: 'finish',
    measure: 'count' as const,
    costPerUnit: 9.0,
    unitLabel: 'bottle',
    color: '#a3593a',
  },
  {
    id: 'pot',
    name: 'Pot',
    category: 'pots',
    role: 'stock',
    measure: 'count' as const,
    costPerUnit: 1.5,
    unitLabel: 'pc',
    color: '#b5651d',
  },
  {
    id: 'growbag',
    name: 'Grow bag',
    category: 'pots',
    role: 'stock',
    measure: 'count' as const,
    costPerUnit: 2.0,
    unitLabel: 'pc',
    color: '#9a6a35',
  },
  {
    id: 'wood-plank',
    name: 'Timber plank',
    category: 'wood',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 6.0,
    unitLabel: 'm',
    color: '#c99a54',
  },
  {
    id: 'stake',
    name: 'Plant stake',
    category: 'wood',
    role: 'stock',
    measure: 'count' as const,
    costPerUnit: 0.5,
    unitLabel: 'pc',
    color: '#b8874a',
  },
];

const partKinds: Profile['partKinds'] = [
  {
    id: 'bed',
    label: 'Garden bed',
    defaultMaterialId: 'mulch',
    defaultLength: 1200,
    defaultWidth: 1200,
    defaultThickness: 30,
    measure: 'area' as const,
  },
  {
    id: 'plant',
    label: 'Plant',
    defaultMaterialId: 'plant',
    defaultLength: 150,
    defaultWidth: 150,
    defaultThickness: 150,
    defaultShape: 'circle',
    measure: 'count' as const,
  },
  {
    id: 'seeds',
    label: 'Seed row',
    defaultMaterialId: 'seed',
    defaultLength: 800,
    defaultWidth: 100,
    defaultThickness: 0,
    defaultShape: 'line',
    measure: 'count' as const,
  },
  {
    id: 'soil',
    label: 'Soil / compost',
    defaultMaterialId: 'soil',
    defaultLength: 400,
    defaultWidth: 200,
    defaultThickness: 100,
    measure: 'count' as const,
  },
  {
    id: 'pot',
    label: 'Pot',
    defaultMaterialId: 'pot',
    defaultLength: 150,
    defaultWidth: 150,
    defaultThickness: 150,
    defaultShape: 'circle',
    measure: 'count' as const,
  },
];

function part(
  kindId: string,
  materialId: string,
  label: string,
  x: number,
  y: number,
  sizeX: number,
  sizeY: number,
  quantity: number,
  dimensions: { length: number; width: number; thickness: number },
): Omit<Part, 'id'> {
  return {
    kindId,
    materialId,
    label,
    position: { x, y },
    size: { x: sizeX, y: sizeY },
    rotation: 0,
    quantity,
    dimensions,
  };
}

const tomatoParts = [
  part('bed', 'mulch', 'Tomato bed', 0, 0, 2000, 1500, 1, { length: 2000, width: 1500, thickness: 30 }),
  part('plant', 'plant', 'Tomato plant', 200, 1700, 150, 150, 20, { length: 150, width: 150, thickness: 150 }),
  part('soil', 'soil', 'Compost', 500, 1700, 400, 200, 6, { length: 400, width: 200, thickness: 100 }),
  part('seeds', 'fertilizer', 'Fertilizer', 100, 1700, 400, 200, 1, { length: 400, width: 200, thickness: 100 }),
];

const raisedBedParts = [
  part('bed', 'mulch', 'Raised bed', 0, 0, 2400, 1200, 1, { length: 2400, width: 1200, thickness: 30 }),
  part('soil', 'soil', 'Compost', 0, 1300, 400, 200, 4, { length: 400, width: 200, thickness: 100 }),
  part('plant', 'plant', 'Vegetable plants', 500, 1300, 150, 150, 6, { length: 150, width: 150, thickness: 150 }),
  part('seeds', 'seed', 'Sown rows', 900, 1300, 800, 100, 2, { length: 800, width: 100, thickness: 0 }),
];

const templates: Template[] = [
  { id: 'tomatoes', name: 'Tomato patch', parts: tomatoParts },
  { id: 'raised-bed', name: 'Raised bed', parts: raisedBedParts },
];

export const gardening: Profile = {
  id: 'gardening',
  name: 'Gardening',
  color: '#3a7d44',
  displayUnit: 'cm',
  precision: 0,
  gridSize: 50,
  snap: true,
  materials,
  partKinds,
  templates,
};