import type { Part, Profile, Template } from '../types';

const materials: Profile['materials'] = [
  {
    id: 'silver-wire',
    name: 'Silver wire 1.0 mm',
    category: 'wire',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 6.0,
    unitLabel: 'm',
    color: '#c7c9ce',
  },
  {
    id: 'gold-wire',
    name: 'Gold wire 0.8 mm',
    category: 'wire',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 55.0,
    unitLabel: 'm',
    color: '#d4af37',
  },
  {
    id: 'copper-wire',
    name: 'Copper wire 1.2 mm',
    category: 'wire',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 2.2,
    unitLabel: 'm',
    color: '#c97b45',
  },
  {
    id: 'silver-sheet',
    name: 'Silver sheet',
    category: 'sheet',
    role: 'stock',
    measure: 'area' as const,
    costPerUnit: 900.0,
    unitLabel: 'm2',
    color: '#d7d8da',
  },
  {
    id: 'gold-sheet',
    name: 'Gold sheet',
    category: 'sheet',
    role: 'stock',
    measure: 'area' as const,
    costPerUnit: 5200.0,
    unitLabel: 'm2',
    color: '#e2c15a',
  },
  {
    id: 'bead',
    name: 'Beads',
    category: 'beads',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 0.15,
    unitLabel: 'pc',
    color: '#5b5f6b',
  },
  {
    id: 'crystal',
    name: 'Crystals',
    category: 'beads',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 0.9,
    unitLabel: 'pc',
    color: '#7aa0c4',
  },
  {
    id: 'pearl',
    name: 'Pearls',
    category: 'beads',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 1.4,
    unitLabel: 'pc',
    color: '#e8e2d2',
  },
  {
    id: 'clasp',
    name: 'Clasps',
    category: 'findings',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 2.2,
    unitLabel: 'pc',
    color: '#9aa0aa',
  },
  {
    id: 'jumpring',
    name: 'Jump rings',
    category: 'findings',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 0.2,
    unitLabel: 'pc',
    color: '#a8adb5',
  },
  {
    id: 'chain',
    name: 'Chain',
    category: 'findings',
    role: 'fixing',
    measure: 'linear' as const,
    costPerUnit: 4.5,
    unitLabel: 'm',
    color: '#c2c6cc',
  },
  {
    id: 'earwire',
    name: 'Ear wires',
    category: 'findings',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 0.9,
    unitLabel: 'pair',
    color: '#b6bcc4',
  },
];

const partKinds: Profile['partKinds'] = [
  {
    id: 'band',
    label: 'Ring band',
    defaultMaterialId: 'silver-wire',
    defaultLength: 21,
    defaultWidth: 3,
    defaultThickness: 1,
    defaultShape: 'circle',
    measure: 'linear' as const,
  },
  {
    id: 'bezel',
    label: 'Bezel',
    defaultMaterialId: 'gold-wire',
    defaultLength: 24,
    defaultWidth: 2,
    defaultThickness: 1,
    measure: 'linear' as const,
  },
  {
    id: 'wire',
    label: 'Wire piece',
    defaultMaterialId: 'silver-wire',
    defaultLength: 60,
    defaultWidth: 1,
    defaultThickness: 1,
    defaultShape: 'line',
    measure: 'linear' as const,
  },
  {
    id: 'sheet',
    label: 'Sheet piece',
    defaultMaterialId: 'silver-sheet',
    defaultLength: 20,
    defaultWidth: 20,
    defaultThickness: 0.5,
    measure: 'area' as const,
  },
  {
    id: 'stones',
    label: 'Bead / crystal set',
    defaultMaterialId: 'bead',
    defaultLength: 40,
    defaultWidth: 20,
    defaultThickness: 10,
    defaultShape: 'circle',
    measure: 'count' as const,
  },
];

function part(
  kindId: string,
  materialId: string,
  label: string,
  x: number,
  y: number,
  sizeX: number,
  sizeY: number,
  quantity: number,
  dimensions: { length: number; width: number; thickness: number },
): Omit<Part, 'id'> {
  return {
    kindId,
    materialId,
    label,
    position: { x, y },
    size: { x: sizeX, y: sizeY },
    rotation: 0,
    quantity,
    dimensions,
  };
}

const ringParts = [
  part('band', 'silver-wire', 'Ring band', 0, 0, 60, 30, 1, { length: 21, width: 3, thickness: 1 }),
  part('bezel', 'gold-wire', 'Bezel', 80, 0, 40, 30, 1, { length: 12, width: 2, thickness: 1 }),
  part('stones', 'bead', 'Beads', 160, 0, 40, 20, 6, { length: 40, width: 20, thickness: 10 }),
];

const pendantParts = [
  part('sheet', 'silver-sheet', 'Pendant plate', 0, 0, 40, 40, 1, { length: 20, width: 20, thickness: 0.5 }),
  part('wire', 'silver-wire', 'Chain wire', 60, 0, 80, 40, 1, { length: 80, width: 1, thickness: 1 }),
  part('stones', 'crystal', 'Crystals', 160, 0, 40, 20, 3, { length: 40, width: 20, thickness: 10 }),
  part('bezel', 'gold-wire', 'Clasp wire', 220, 0, 40, 30, 1, { length: 12, width: 2, thickness: 1 }),
];

const templates: Template[] = [
  { id: 'ring', name: 'Simple ring', parts: ringParts },
  { id: 'pendant', name: 'Pendant', parts: pendantParts },
];

export const jewelry: Profile = {
  id: 'jewelry',
  name: 'Jewelry',
  color: '#8e6ad8',
  displayUnit: 'mm',
  precision: 1,
  gridSize: 0.5,
  snap: true,
  materials,
  partKinds,
  templates,
};