import type { Part, Profile, Template } from '../types';

const materials: Profile['materials'] = [
  {
    id: 'paver',
    name: 'Concrete paver',
    category: 'paving',
    role: 'stock',
    measure: 'area' as const,
    costPerUnit: 28.0,
    unitLabel: 'm2',
    color: '#b0aaa0',
  },
  {
    id: 'flagstone',
    name: 'Flagstone',
    category: 'paving',
    role: 'stock',
    measure: 'area' as const,
    costPerUnit: 55.0,
    unitLabel: 'm2',
    color: '#b8ae9c',
  },
  {
    id: 'brick',
    name: 'Paving brick',
    category: 'paving',
    role: 'stock',
    measure: 'area' as const,
    costPerUnit: 32.0,
    unitLabel: 'm2',
    color: '#a06850',
  },
  {
    id: 'sand',
    name: 'Bedding sand',
    category: 'aggregate',
    role: 'stock',
    measure: 'area' as const,
    costPerUnit: 4.0,
    unitLabel: 'm2',
    color: '#c9b58f',
  },
  {
    id: 'gravel',
    name: 'Decorative gravel',
    category: 'aggregate',
    role: 'stock',
    measure: 'area' as const,
    costPerUnit: 9.0,
    unitLabel: 'm2',
    color: '#a8a49c',
  },
  {
    id: 'topsoil',
    name: 'Topsoil',
    category: 'aggregate',
    role: 'stock',
    measure: 'area' as const,
    costPerUnit: 12.0,
    unitLabel: 'm2',
    color: '#7a5a3a',
  },
  {
    id: 'membrane',
    name: 'Weed membrane',
    category: 'subbase',
    role: 'stock',
    measure: 'area' as const,
    costPerUnit: 2.5,
    unitLabel: 'm2',
    color: '#3f4f3a',
  },
  {
    id: 'edging',
    name: 'Edging / kerb',
    category: 'edge',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 7.0,
    unitLabel: 'm',
    color: '#8b95a1',
  },
  {
    id: 'sleeper',
    name: 'Timber sleeper',
    category: 'edge',
    role: 'stock',
    measure: 'count' as const,
    costPerUnit: 18.0,
    unitLabel: 'pc',
    color: '#8a5a33',
  },
  {
    id: 'plant',
    name: 'Plant / shrub',
    category: 'planting',
    role: 'stock',
    measure: 'count' as const,
    costPerUnit: 6.0,
    unitLabel: 'pc',
    color: '#2f6d38',
  },
  {
    id: 'bulb',
    name: 'Bulbs',
    category: 'planting',
    role: 'stock',
    measure: 'count' as const,
    costPerUnit: 0.35,
    unitLabel: 'pc',
    color: '#c9a227',
  },
  {
    id: 'drip-line',
    name: 'Drip irrigation line',
    category: 'irrigation',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 1.4,
    unitLabel: 'm',
    color: '#3a5f7a',
  },
];

const partKinds: Profile['partKinds'] = [
  {
    id: 'paved',
    label: 'Paved area',
    defaultMaterialId: 'paver',
    defaultLength: 600,
    defaultWidth: 600,
    defaultThickness: 50,
    measure: 'area' as const,
  },
  {
    id: 'bed',
    label: 'Planting bed',
    defaultMaterialId: 'topsoil',
    defaultLength: 1200,
    defaultWidth: 1200,
    defaultThickness: 100,
    measure: 'area' as const,
  },
  {
    id: 'edge',
    label: 'Edging',
    defaultMaterialId: 'edging',
    defaultLength: 1000,
    defaultWidth: 50,
    defaultThickness: 150,
    defaultShape: 'line',
    measure: 'linear' as const,
  },
  {
    id: 'plant',
    label: 'Plant',
    defaultMaterialId: 'plant',
    defaultLength: 200,
    defaultWidth: 200,
    defaultThickness: 200,
    defaultShape: 'circle',
    measure: 'count' as const,
  },
  {
    id: 'irrigation',
    label: 'Irrigation line',
    defaultMaterialId: 'drip-line',
    defaultLength: 1000,
    defaultWidth: 16,
    defaultThickness: 16,
    defaultShape: 'line',
    measure: 'linear' as const,
  },
];

function part(
  kindId: string,
  materialId: string,
  label: string,
  x: number,
  y: number,
  sizeX: number,
  sizeY: number,
  quantity: number,
  dimensions: { length: number; width: number; thickness: number },
): Omit<Part, 'id'> {
  return {
    kindId,
    materialId,
    label,
    position: { x, y },
    size: { x: sizeX, y: sizeY },
    rotation: 0,
    quantity,
    dimensions,
  };
}

const pathParts: Omit<Part, 'id'>[] = [
  part('paved', 'paver', 'Path', 0, 0, 6000, 900, 1, { length: 6000, width: 900, thickness: 50 }),
  part('paved', 'sand', 'Bedding sand', 0, 1000, 6000, 900, 1, { length: 6000, width: 900, thickness: 30 }),
  part('edge', 'edging', 'Edging', 0, 2000, 1000, 50, 14, { length: 1000, width: 50, thickness: 150 }),
  part('bed', 'membrane', 'Weed membrane', 0, 2100, 6000, 900, 1, { length: 6000, width: 900, thickness: 2 }),
];

const raisedBedParts: Omit<Part, 'id'>[] = [
  part('bed', 'topsoil', 'Topsoil', 0, 0, 2400, 1200, 1, { length: 2400, width: 1200, thickness: 300 }),
  part('edge', 'sleeper', 'Sleeper', 0, 1300, 1200, 200, 6, { length: 1200, width: 200, thickness: 100 }),
  part('bed', 'membrane', 'Weed membrane', 0, 2400, 2400, 1200, 1, { length: 2400, width: 1200, thickness: 2 }),
  part('plant', 'plant', 'Plants', 0, 2500, 200, 200, 8, { length: 200, width: 200, thickness: 200 }),
  part('irrigation', 'drip-line', 'Drip line', 0, 2600, 1000, 16, 8, { length: 1000, width: 16, thickness: 16 }),
];

const retainingWallParts: Omit<Part, 'id'>[] = [
  part('paved', 'brick', 'Wall face', 0, 0, 4000, 900, 1, { length: 4000, width: 900, thickness: 100 }),
  part('paved', 'gravel', 'Backfill gravel', 0, 1000, 4000, 300, 1, { length: 4000, width: 300, thickness: 150 }),
  part('bed', 'topsoil', 'Retained soil', 0, 2000, 4000, 1200, 1, { length: 4000, width: 1200, thickness: 400 }),
  part('plant', 'bulb', 'Bulbs', 0, 2100, 100, 100, 60, { length: 100, width: 100, thickness: 100 }),
];

const templates: Template[] = [
  { id: 'path', name: 'Garden path', parts: pathParts },
  { id: 'raised-bed', name: 'Raised bed', parts: raisedBedParts },
  { id: 'retaining-wall', name: 'Retaining wall', parts: retainingWallParts },
];

export const landscaping: Profile = {
  id: 'landscaping',
  name: 'Landscaping',
  color: '#7a9a3d',
  displayUnit: 'mm',
  precision: 0,
  gridSize: 50,
  snap: true,
  materials,
  partKinds,
  templates,
};
