import type { Part, Profile, Template } from '../types';

const materials: Profile['materials'] = [
  {
    id: 'veg-tan',
    name: 'Vegetable-tanned hide',
    category: 'leather',
    role: 'stock',
    measure: 'area' as const,
    costPerUnit: 180.0,
    unitLabel: 'm2',
    color: '#c08a4a',
  },
  {
    id: 'chrome-tan',
    name: 'Chrome-tanned hide',
    category: 'leather',
    role: 'stock',
    measure: 'area' as const,
    costPerUnit: 120.0,
    unitLabel: 'm2',
    color: '#8a5a33',
  },
  {
    id: 'suede',
    name: 'Suede lining',
    category: 'lining',
    role: 'stock',
    measure: 'area' as const,
    costPerUnit: 90.0,
    unitLabel: 'm2',
    color: '#b08050',
  },
  {
    id: 'canvas',
    name: 'Waxed canvas',
    category: 'lining',
    role: 'stock',
    measure: 'area' as const,
    costPerUnit: 28.0,
    unitLabel: 'm2',
    color: '#5a6a4a',
  },
  {
    id: 'strap',
    name: 'Leather strap',
    category: 'strap',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 12.0,
    unitLabel: 'm',
    color: '#a0703a',
  },
  {
    id: 'edge-paint',
    name: 'Edge paint',
    category: 'finish',
    role: 'finish',
    measure: 'linear' as const,
    costPerUnit: 0.8,
    unitLabel: 'm',
    color: '#3a2a1a',
  },
  {
    id: 'wax',
    name: 'Beeswax finish',
    category: 'finish',
    role: 'finish',
    measure: 'area' as const,
    costPerUnit: 6.0,
    unitLabel: 'm2',
    color: '#d8c48f',
  },
  {
    id: 'thread-waxed',
    name: 'Waxed thread',
    category: 'thread',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 8.0,
    unitLabel: 'spool',
    color: '#c9a227',
  },
  {
    id: 'buckle',
    name: 'Buckle',
    category: 'hardware',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 4.5,
    unitLabel: 'pc',
    color: '#8b7a3a',
  },
  {
    id: 'd-ring',
    name: 'D-ring',
    category: 'hardware',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 1.2,
    unitLabel: 'pc',
    color: '#9aa0aa',
  },
  {
    id: 'rivet',
    name: 'Rivet',
    category: 'hardware',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 0.1,
    unitLabel: 'pc',
    color: '#a8adb5',
  },
  {
    id: 'snap',
    name: 'Snap fastener',
    category: 'hardware',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 0.6,
    unitLabel: 'pc',
    color: '#b0651d',
  },
  {
    id: 'clasp',
    name: 'Bag clasp',
    category: 'hardware',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 6.0,
    unitLabel: 'pc',
    color: '#c2a24a',
  },
];

const partKinds: Profile['partKinds'] = [
  {
    id: 'panel',
    label: 'Leather panel',
    defaultMaterialId: 'veg-tan',
    defaultLength: 300,
    defaultWidth: 200,
    defaultThickness: 3,
    measure: 'area' as const,
  },
  {
    id: 'strap',
    label: 'Strap',
    defaultMaterialId: 'strap',
    defaultLength: 800,
    defaultWidth: 25,
    defaultThickness: 3,
    defaultShape: 'line',
    measure: 'linear' as const,
  },
  {
    id: 'lining',
    label: 'Lining',
    defaultMaterialId: 'suede',
    defaultLength: 250,
    defaultWidth: 150,
    defaultThickness: 1,
    measure: 'area' as const,
  },
  {
    id: 'hardware',
    label: 'Hardware',
    defaultMaterialId: 'buckle',
    defaultLength: 40,
    defaultWidth: 40,
    defaultThickness: 10,
    defaultShape: 'circle',
    measure: 'count' as const,
  },
  {
    id: 'finish',
    label: 'Finish',
    defaultMaterialId: 'wax',
    defaultLength: 300,
    defaultWidth: 200,
    defaultThickness: 1,
    measure: 'area' as const,
  },
];

function part(
  kindId: string,
  materialId: string,
  label: string,
  x: number,
  y: number,
  sizeX: number,
  sizeY: number,
  quantity: number,
  dimensions: { length: number; width: number; thickness: number },
): Omit<Part, 'id'> {
  return {
    kindId,
    materialId,
    label,
    position: { x, y },
    size: { x: sizeX, y: sizeY },
    rotation: 0,
    quantity,
    dimensions,
  };
}

const beltParts: Omit<Part, 'id'>[] = [
  part('strap', 'strap', 'Belt strap', 0, 0, 1000, 25, 1, { length: 1100, width: 38, thickness: 4 }),
  part('panel', 'veg-tan', 'Tip keeper', 0, 100, 300, 200, 1, { length: 80, width: 40, thickness: 4 }),
  part('hardware', 'buckle', 'Buckle', 0, 200, 40, 40, 1, { length: 40, width: 40, thickness: 10 }),
  part('hardware', 'rivet', 'Rivets', 80, 200, 10, 10, 3, { length: 10, width: 10, thickness: 8 }),
  part('hardware', 'snap', 'Snap', 140, 200, 15, 15, 2, { length: 15, width: 15, thickness: 8 }),
  part('finish', 'edge-paint', 'Edge paint', 200, 200, 1000, 5, 2, { length: 2400, width: 5, thickness: 1 }),
  part('finish', 'wax', 'Beeswax', 300, 200, 300, 200, 1, { length: 1100, width: 40, thickness: 1 }),
];

const cardWalletParts: Omit<Part, 'id'>[] = [
  part('panel', 'veg-tan', 'Outer shell', 0, 0, 300, 200, 1, { length: 200, width: 90, thickness: 2 }),
  part('panel', 'veg-tan', 'Card slot', 0, 100, 300, 200, 3, { length: 110, width: 70, thickness: 2 }),
  part('lining', 'suede', 'Lining', 0, 200, 250, 150, 1, { length: 200, width: 90, thickness: 1 }),
  part('hardware', 'rivet', 'Rivets', 0, 300, 10, 10, 2, { length: 10, width: 10, thickness: 8 }),
  part('hardware', 'thread-waxed', 'Waxed thread', 60, 300, 10, 10, 1, { length: 10, width: 10, thickness: 10 }),
  part('finish', 'edge-paint', 'Edge paint', 120, 300, 500, 5, 1, { length: 600, width: 5, thickness: 1 }),
  part('finish', 'wax', 'Beeswax', 220, 300, 300, 200, 1, { length: 200, width: 90, thickness: 1 }),
];

const toteBagParts: Omit<Part, 'id'>[] = [
  part('panel', 'chrome-tan', 'Front panel', 0, 0, 300, 200, 1, { length: 350, width: 300, thickness: 2 }),
  part('panel', 'chrome-tan', 'Back panel', 0, 100, 300, 200, 1, { length: 350, width: 300, thickness: 2 }),
  part('panel', 'chrome-tan', 'Gusset', 0, 200, 300, 200, 2, { length: 350, width: 100, thickness: 2 }),
  part('lining', 'canvas', 'Lining', 0, 300, 250, 150, 1, { length: 400, width: 500, thickness: 1 }),
  part('strap', 'strap', 'Handle', 0, 400, 800, 25, 2, { length: 600, width: 25, thickness: 4 }),
  part('hardware', 'd-ring', 'D-ring', 0, 500, 25, 25, 2, { length: 25, width: 25, thickness: 5 }),
  part('hardware', 'clasp', 'Clasp', 60, 500, 30, 30, 1, { length: 30, width: 30, thickness: 12 }),
  part('hardware', 'rivet', 'Rivets', 120, 500, 10, 10, 8, { length: 10, width: 10, thickness: 8 }),
  part('hardware', 'thread-waxed', 'Waxed thread', 180, 500, 10, 10, 2, { length: 10, width: 10, thickness: 10 }),
  part('finish', 'edge-paint', 'Edge paint', 240, 500, 500, 5, 1, { length: 1800, width: 5, thickness: 1 }),
];

const templates: Template[] = [
  { id: 'belt', name: 'Belt', parts: beltParts },
  { id: 'card-wallet', name: 'Card wallet', parts: cardWalletParts },
  { id: 'tote-bag', name: 'Tote bag', parts: toteBagParts },
];

export const leatherworking: Profile = {
  id: 'leatherworking',
  name: 'Leatherworking',
  color: '#a4663a',
  displayUnit: 'mm',
  precision: 0,
  gridSize: 5,
  snap: true,
  materials,
  partKinds,
  templates,
};
