import type { Part, Profile, Template } from '../types';

const materials: Profile['materials'] = [
  {
    id: 'shs-40',
    name: 'Box section 40 x 40 x 3',
    category: 'stock',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 12.0,
    unitLabel: 'm',
    color: '#6b7280',
    stock: [{ length: 6000 }],
    kerf: 3,
  },
  {
    id: 'shs-25',
    name: 'Box section 25 x 25 x 2',
    category: 'stock',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 7.0,
    unitLabel: 'm',
    color: '#78808c',
    stock: [{ length: 6000 }],
    kerf: 3,
  },
  {
    id: 'tube-33',
    name: 'Round tube 33 mm',
    category: 'stock',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 9.0,
    unitLabel: 'm',
    color: '#8b95a1',
    stock: [{ length: 6000 }],
    kerf: 3,
  },
  {
    id: 'angle-40',
    name: 'Angle iron 40 x 40',
    category: 'stock',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 8.5,
    unitLabel: 'm',
    color: '#5a626c',
    stock: [{ length: 6000 }],
    kerf: 3,
  },
  {
    id: 'flat-40',
    name: 'Flat bar 40 x 5',
    category: 'stock',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 6.0,
    unitLabel: 'm',
    color: '#9aa0aa',
    stock: [{ length: 6000 }],
    kerf: 3,
  },
  {
    id: 'plate-3',
    name: 'Steel plate 3 mm',
    category: 'plate',
    role: 'stock',
    measure: 'area' as const,
    costPerUnit: 45.0,
    unitLabel: 'm2',
    color: '#7a828c',
    stock: [{ length: 1000, width: 2000 }],
    kerf: 3,
  },
  {
    id: 'plate-5',
    name: 'Steel plate 5 mm',
    category: 'plate',
    role: 'stock',
    measure: 'area' as const,
    costPerUnit: 68.0,
    unitLabel: 'm2',
    color: '#6e7a86',
    stock: [{ length: 1000, width: 2000 }],
    kerf: 3,
  },
  {
    id: 'bolt-m10',
    name: 'Bolt M10',
    category: 'fixing',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 0.7,
    unitLabel: 'pc',
    color: '#4a5560',
  },
  {
    id: 'nut-m10',
    name: 'Nut M10',
    category: 'fixing',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 0.15,
    unitLabel: 'pc',
    color: '#5a626c',
  },
  {
    id: 'electrode',
    name: 'Welding electrode',
    category: 'consumable',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 0.4,
    unitLabel: 'pc',
    color: '#b0a030',
  },
  {
    id: 'wire-mig',
    name: 'MIG wire',
    category: 'consumable',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 18.0,
    unitLabel: 'spool',
    color: '#c9a227',
  },
  {
    id: 'grinder-disc',
    name: 'Cutting disc',
    category: 'consumable',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 1.5,
    unitLabel: 'pc',
    color: '#a03020',
  },
  {
    id: 'primer',
    name: 'Etch primer',
    category: 'finish',
    role: 'finish',
    measure: 'area' as const,
    costPerUnit: 8.0,
    unitLabel: 'm2',
    color: '#8a5a33',
  },
  {
    id: 'paint',
    name: 'Metal paint',
    category: 'finish',
    role: 'finish',
    measure: 'area' as const,
    costPerUnit: 10.0,
    unitLabel: 'm2',
    color: '#3a5f7a',
  },
];

const partKinds: Profile['partKinds'] = [
  {
    id: 'stock',
    label: 'Stock',
    defaultMaterialId: 'shs-40',
    defaultLength: 1000,
    defaultWidth: 40,
    defaultThickness: 40,
    defaultShape: 'line',
    measure: 'linear' as const,
  },
  {
    id: 'plate',
    label: 'Plate',
    defaultMaterialId: 'plate-3',
    defaultLength: 300,
    defaultWidth: 300,
    defaultThickness: 3,
    measure: 'area' as const,
  },
  {
    id: 'fixing',
    label: 'Fixing',
    defaultMaterialId: 'bolt-m10',
    defaultLength: 20,
    defaultWidth: 20,
    defaultThickness: 20,
    defaultShape: 'circle',
    measure: 'count' as const,
  },
  {
    id: 'consumable',
    label: 'Consumable',
    defaultMaterialId: 'electrode',
    defaultLength: 10,
    defaultWidth: 10,
    defaultThickness: 10,
    defaultShape: 'circle',
    measure: 'count' as const,
  },
  {
    id: 'finish',
    label: 'Finish',
    defaultMaterialId: 'primer',
    defaultLength: 300,
    defaultWidth: 200,
    defaultThickness: 1,
    measure: 'area' as const,
  },
];

function part(
  kindId: string,
  materialId: string,
  label: string,
  x: number,
  y: number,
  sizeX: number,
  sizeY: number,
  quantity: number,
  dimensions: { length: number; width: number; thickness: number },
): Omit<Part, 'id'> {
  return {
    kindId,
    materialId,
    label,
    position: { x, y },
    size: { x: sizeX, y: sizeY },
    rotation: 0,
    quantity,
    dimensions,
  };
}

const tableFrameParts: Omit<Part, 'id'>[] = [
  part('stock', 'shs-40', 'Long rail', 0, 0, 1000, 40, 2, { length: 1500, width: 40, thickness: 40 }),
  part('stock', 'shs-40', 'Short rail', 0, 60, 1000, 40, 2, { length: 800, width: 40, thickness: 40 }),
  part('stock', 'shs-40', 'Leg', 0, 120, 40, 40, 4, { length: 720, width: 40, thickness: 40 }),
  part('stock', 'shs-25', 'Cross brace', 0, 180, 1000, 25, 2, { length: 800, width: 25, thickness: 25 }),
  part('plate', 'plate-3', 'Foot plate', 0, 240, 300, 300, 4, { length: 120, width: 120, thickness: 3 }),
  part('fixing', 'bolt-m10', 'Bolt', 0, 300, 20, 20, 16, { length: 20, width: 20, thickness: 20 }),
  part('fixing', 'nut-m10', 'Nut', 60, 300, 20, 20, 16, { length: 20, width: 20, thickness: 20 }),
  part('consumable', 'electrode', 'Electrodes', 120, 300, 10, 10, 20, { length: 10, width: 10, thickness: 10 }),
  part('consumable', 'grinder-disc', 'Cutting discs', 180, 300, 10, 10, 4, { length: 10, width: 10, thickness: 10 }),
  part('finish', 'primer', 'Etch primer', 240, 300, 300, 200, 1, { length: 4600, width: 100, thickness: 1 }),
  part('finish', 'paint', 'Metal paint', 300, 300, 300, 200, 1, { length: 4600, width: 100, thickness: 1 }),
];

const gateParts: Omit<Part, 'id'>[] = [
  part('stock', 'shs-40', 'Gate frame', 0, 0, 1000, 40, 2, { length: 900, width: 40, thickness: 40 }),
  part('stock', 'flat-40', 'Vertical bar', 0, 60, 1000, 40, 12, { length: 800, width: 40, thickness: 5 }),
  part('stock', 'angle-40', 'Hinge rail', 0, 120, 1000, 40, 1, { length: 900, width: 40, thickness: 5 }),
  part('consumable', 'wire-mig', 'MIG wire', 0, 180, 10, 10, 1, { length: 10, width: 10, thickness: 10 }),
  part('fixing', 'bolt-m10', 'Bolt', 60, 180, 20, 20, 6, { length: 20, width: 20, thickness: 20 }),
  part('finish', 'paint', 'Metal paint', 120, 180, 300, 200, 1, { length: 2600, width: 100, thickness: 1 }),
];

const bracketParts: Omit<Part, 'id'>[] = [
  part('plate', 'plate-5', 'Gusset plate', 0, 0, 300, 300, 2, { length: 150, width: 150, thickness: 5 }),
  part('stock', 'angle-40', 'Angle leg', 0, 60, 1000, 40, 2, { length: 200, width: 40, thickness: 5 }),
  part('consumable', 'electrode', 'Electrodes', 0, 120, 10, 10, 6, { length: 10, width: 10, thickness: 10 }),
  part('fixing', 'bolt-m10', 'Bolt', 60, 120, 20, 20, 4, { length: 20, width: 20, thickness: 20 }),
  part('finish', 'primer', 'Etch primer', 120, 120, 300, 200, 1, { length: 700, width: 150, thickness: 1 }),
];

const templates: Template[] = [
  { id: 'table-frame', name: 'Table frame', parts: tableFrameParts },
  { id: 'gate', name: 'Garden gate', parts: gateParts },
  { id: 'bracket', name: 'Bracket', parts: bracketParts },
];

export const metalwork: Profile = {
  id: 'metalwork',
  name: 'Metalwork',
  color: '#6b7280',
  displayUnit: 'mm',
  precision: 0,
  gridSize: 5,
  snap: true,
  materials,
  partKinds,
  templates,
};
