import type { Part, Profile, Template } from '../types';

const materials: Profile['materials'] = [
  {
    id: 'pipe-15',
    name: 'Copper pipe 15 mm',
    category: 'pipe',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 6.5,
    unitLabel: 'm',
    color: '#c97b45',
  },
  {
    id: 'pipe-22',
    name: 'Copper pipe 22 mm',
    category: 'pipe',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 9.0,
    unitLabel: 'm',
    color: '#b87333',
  },
  {
    id: 'pex-16',
    name: 'PEX pipe 16 mm',
    category: 'pipe',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 1.6,
    unitLabel: 'm',
    color: '#c9c4bd',
  },
  {
    id: 'waste-40',
    name: 'Waste pipe 40 mm',
    category: 'waste',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 3.2,
    unitLabel: 'm',
    color: '#a8adb5',
  },
  {
    id: 'insul-15',
    name: 'Pipe insulation 15 mm',
    category: 'insulation',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 1.8,
    unitLabel: 'm',
    color: '#d8d2c4',
  },
  {
    id: 'elbow-15',
    name: 'Elbow 15 mm',
    category: 'fitting',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 1.2,
    unitLabel: 'pc',
    color: '#b0651d',
  },
  {
    id: 'tee-15',
    name: 'Tee 15 mm',
    category: 'fitting',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 1.6,
    unitLabel: 'pc',
    color: '#a35c1a',
  },
  {
    id: 'coupler',
    name: 'Straight coupler',
    category: 'fitting',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 0.9,
    unitLabel: 'pc',
    color: '#9a5518',
  },
  {
    id: 'valve',
    name: 'Isolation valve',
    category: 'fitting',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 5.5,
    unitLabel: 'pc',
    color: '#78808c',
  },
  {
    id: 'clip',
    name: 'Pipe clip',
    category: 'fixing',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 0.15,
    unitLabel: 'pc',
    color: '#8b95a1',
  },
  {
    id: 'tap',
    name: 'Outdoor tap',
    category: 'fixture',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 14.0,
    unitLabel: 'pc',
    color: '#5a6a8a',
  },
  {
    id: 'sink-trap',
    name: 'Sink trap',
    category: 'fixture',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 8.5,
    unitLabel: 'pc',
    color: '#b6bcc4',
  },
  {
    id: 'ptfe',
    name: 'PTFE tape',
    category: 'consumable',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 1.0,
    unitLabel: 'roll',
    color: '#e8e2d2',
  },
];

const partKinds: Profile['partKinds'] = [
  {
    id: 'pipe',
    label: 'Pipe run',
    defaultMaterialId: 'pipe-15',
    defaultLength: 1000,
    defaultWidth: 15,
    defaultThickness: 15,
    defaultShape: 'line',
    measure: 'linear' as const,
  },
  {
    id: 'fitting',
    label: 'Fitting',
    defaultMaterialId: 'elbow-15',
    defaultLength: 40,
    defaultWidth: 40,
    defaultThickness: 40,
    defaultShape: 'circle',
    measure: 'count' as const,
  },
  {
    id: 'fixture',
    label: 'Fixture',
    defaultMaterialId: 'tap',
    defaultLength: 120,
    defaultWidth: 120,
    defaultThickness: 120,
    measure: 'count' as const,
  },
  {
    id: 'insulation',
    label: 'Insulation',
    defaultMaterialId: 'insul-15',
    defaultLength: 1000,
    defaultWidth: 25,
    defaultThickness: 25,
    defaultShape: 'line',
    measure: 'linear' as const,
  },
];

function part(
  kindId: string,
  materialId: string,
  label: string,
  x: number,
  y: number,
  sizeX: number,
  sizeY: number,
  quantity: number,
  dimensions: { length: number; width: number; thickness: number },
): Omit<Part, 'id'> {
  return {
    kindId,
    materialId,
    label,
    position: { x, y },
    size: { x: sizeX, y: sizeY },
    rotation: 0,
    quantity,
    dimensions,
  };
}

const gardenTapParts: Omit<Part, 'id'>[] = [
  part('pipe', 'pipe-15', 'Supply run', 0, 0, 1000, 15, 6, { length: 1000, width: 15, thickness: 15 }),
  part('insulation', 'insul-15', 'Pipe insulation', 0, 100, 1000, 25, 6, { length: 1000, width: 25, thickness: 25 }),
  part('fitting', 'elbow-15', 'Elbow', 0, 200, 40, 40, 2, { length: 40, width: 40, thickness: 40 }),
  part('fitting', 'tee-15', 'Tee', 100, 200, 40, 40, 1, { length: 40, width: 40, thickness: 40 }),
  part('fitting', 'valve', 'Isolation valve', 200, 200, 60, 60, 1, { length: 60, width: 60, thickness: 60 }),
  part('fixture', 'tap', 'Outdoor tap', 300, 200, 120, 120, 1, { length: 120, width: 120, thickness: 120 }),
  part('fitting', 'clip', 'Pipe clips', 400, 200, 30, 30, 12, { length: 30, width: 30, thickness: 30 }),
  part('fitting', 'ptfe', 'PTFE tape', 500, 200, 40, 40, 1, { length: 40, width: 40, thickness: 40 }),
];

const sinkWasteParts: Omit<Part, 'id'>[] = [
  part('pipe', 'waste-40', 'Waste run', 0, 0, 1000, 40, 2, { length: 1000, width: 40, thickness: 40 }),
  part('fitting', 'coupler', 'Coupler', 0, 100, 50, 50, 2, { length: 50, width: 50, thickness: 50 }),
  part('fitting', 'elbow-15', 'Bend', 100, 100, 50, 50, 3, { length: 50, width: 50, thickness: 50 }),
  part('fixture', 'sink-trap', 'Sink trap', 200, 100, 120, 120, 1, { length: 120, width: 120, thickness: 120 }),
  part('fitting', 'clip', 'Pipe clips', 300, 100, 30, 30, 6, { length: 30, width: 30, thickness: 30 }),
];

const dripZoneParts: Omit<Part, 'id'>[] = [
  part('pipe', 'pex-16', 'Supply line', 0, 0, 1000, 16, 8, { length: 1000, width: 16, thickness: 16 }),
  part('fitting', 'tee-15', 'Tee', 0, 100, 40, 40, 4, { length: 40, width: 40, thickness: 40 }),
  part('fitting', 'valve', 'Zone valve', 100, 100, 60, 60, 1, { length: 60, width: 60, thickness: 60 }),
  part('pipe', 'pipe-15', 'Manifold feed', 200, 100, 1000, 15, 3, { length: 1000, width: 15, thickness: 15 }),
  part('fitting', 'clip', 'Pipe clips', 300, 100, 30, 30, 16, { length: 30, width: 30, thickness: 30 }),
  part('fitting', 'ptfe', 'PTFE tape', 400, 100, 40, 40, 2, { length: 40, width: 40, thickness: 40 }),
];

const templates: Template[] = [
  { id: 'garden-tap', name: 'Garden tap', parts: gardenTapParts },
  { id: 'sink-waste', name: 'Sink waste', parts: sinkWasteParts },
  { id: 'drip-zone', name: 'Drip zone', parts: dripZoneParts },
];

export const plumbing: Profile = {
  id: 'plumbing',
  name: 'Plumbing',
  color: '#3d8fa8',
  displayUnit: 'mm',
  precision: 0,
  gridSize: 5,
  snap: true,
  materials,
  partKinds,
  templates,
};
