import type { Part, Profile, Template } from '../types';

const materials: Profile['materials'] = [
  {
    id: 'tile-ceramic',
    name: 'Ceramic tile',
    category: 'tile',
    role: 'stock',
    measure: 'area' as const,
    costPerUnit: 22.0,
    unitLabel: 'm2',
    color: '#cfd6dd',
  },
  {
    id: 'tile-porcelain',
    name: 'Porcelain tile',
    category: 'tile',
    role: 'stock',
    measure: 'area' as const,
    costPerUnit: 35.0,
    unitLabel: 'm2',
    color: '#e6e9ee',
  },
  {
    id: 'tile-natural',
    name: 'Natural stone tile',
    category: 'tile',
    role: 'stock',
    measure: 'area' as const,
    costPerUnit: 60.0,
    unitLabel: 'm2',
    color: '#cbb79a',
  },
  {
    id: 'mosaic',
    name: 'Mosaic sheet',
    category: 'tile',
    role: 'stock',
    measure: 'area' as const,
    costPerUnit: 48.0,
    unitLabel: 'm2',
    color: '#b9c4c4',
  },
  {
    id: 'adhesive',
    name: 'Tile adhesive',
    category: 'adhesive',
    role: 'finish',
    measure: 'area' as const,
    costPerUnit: 6.5,
    unitLabel: 'm2',
    color: '#8a8f94',
  },
  {
    id: 'grout',
    name: 'Grout',
    category: 'adhesive',
    role: 'finish',
    measure: 'area' as const,
    costPerUnit: 2.8,
    unitLabel: 'm2',
    color: '#b9b4a8',
  },
  {
    id: 'underlay',
    name: 'Underlay / membrane',
    category: 'subfloor',
    role: 'stock',
    measure: 'area' as const,
    costPerUnit: 8.0,
    unitLabel: 'm2',
    color: '#4a5a6a',
  },
  {
    id: 'backerboard',
    name: 'Backer board',
    category: 'subfloor',
    role: 'stock',
    measure: 'area' as const,
    costPerUnit: 12.0,
    unitLabel: 'm2',
    color: '#c4bfae',
  },
  {
    id: 'trim',
    name: 'Edge trim',
    category: 'trim',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 4.5,
    unitLabel: 'm',
    color: '#b0b7c4',
  },
  {
    id: 'movement',
    name: 'Movement joint',
    category: 'trim',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 6.0,
    unitLabel: 'm',
    color: '#9aa0aa',
  },
  {
    id: 'spacer',
    name: 'Tile spacer',
    category: 'consumable',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 0.03,
    unitLabel: 'pc',
    color: '#d8d2c4',
  },
  {
    id: 'clip',
    name: 'Levelling clip',
    category: 'consumable',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 0.12,
    unitLabel: 'pc',
    color: '#c2c6cc',
  },
  {
    id: 'sealer',
    name: 'Stone sealer',
    category: 'finish',
    role: 'finish',
    measure: 'area' as const,
    costPerUnit: 7.0,
    unitLabel: 'm2',
    color: '#d7d2c8',
  },
];

const partKinds: Profile['partKinds'] = [
  {
    id: 'tile',
    label: 'Tile field',
    defaultMaterialId: 'tile-ceramic',
    defaultLength: 300,
    defaultWidth: 300,
    defaultThickness: 8,
    measure: 'area' as const,
  },
  {
    id: 'trim',
    label: 'Trim / joint',
    defaultMaterialId: 'trim',
    defaultLength: 1000,
    defaultWidth: 20,
    defaultThickness: 8,
    defaultShape: 'line',
    measure: 'linear' as const,
  },
  {
    id: 'fix',
    label: 'Spacers / clips',
    defaultMaterialId: 'spacer',
    defaultLength: 20,
    defaultWidth: 20,
    defaultThickness: 5,
    defaultShape: 'circle',
    measure: 'count' as const,
  },
  {
    id: 'substrate',
    label: 'Substrate',
    defaultMaterialId: 'underlay',
    defaultLength: 1200,
    defaultWidth: 800,
    defaultThickness: 6,
    measure: 'area' as const,
  },
  {
    id: 'finish',
    label: 'Sealer',
    defaultMaterialId: 'sealer',
    defaultLength: 400,
    defaultWidth: 300,
    defaultThickness: 1,
    measure: 'area' as const,
  },
];

function part(
  kindId: string,
  materialId: string,
  label: string,
  x: number,
  y: number,
  sizeX: number,
  sizeY: number,
  quantity: number,
  dimensions: { length: number; width: number; thickness: number },
): Omit<Part, 'id'> {
  return {
    kindId,
    materialId,
    label,
    position: { x, y },
    size: { x: sizeX, y: sizeY },
    rotation: 0,
    quantity,
    dimensions,
  };
}

const bathroomFloorParts: Omit<Part, 'id'>[] = [
  part('tile', 'tile-porcelain', 'Floor tile', 0, 0, 2000, 1500, 1, { length: 2000, width: 1500, thickness: 10 }),
  part('substrate', 'underlay', 'Underlay', 0, 1600, 2000, 1500, 1, { length: 2000, width: 1500, thickness: 6 }),
  part('substrate', 'backerboard', 'Backer board', 0, 3200, 1200, 800, 4, { length: 1200, width: 800, thickness: 6 }),
  part('trim', 'trim', 'Edge trim', 0, 4100, 1000, 20, 7, { length: 1000, width: 20, thickness: 8 }),
  part('fix', 'spacer', 'Spacers', 0, 4200, 20, 20, 400, { length: 20, width: 20, thickness: 5 }),
  part('fix', 'clip', 'Levelling clips', 60, 4200, 20, 20, 120, { length: 20, width: 20, thickness: 5 }),
  part('finish', 'sealer', 'Stone sealer', 120, 4200, 400, 300, 1, { length: 2000, width: 1500, thickness: 1 }),
];

const splashbackParts: Omit<Part, 'id'>[] = [
  part('tile', 'mosaic', 'Splashback tile', 0, 0, 2400, 600, 1, { length: 2400, width: 600, thickness: 8 }),
  part('substrate', 'backerboard', 'Backer board', 0, 700, 1200, 800, 2, { length: 1200, width: 800, thickness: 6 }),
  part('trim', 'trim', 'Edge trim', 0, 1600, 1000, 20, 3, { length: 1000, width: 20, thickness: 8 }),
  part('fix', 'spacer', 'Spacers', 0, 1700, 20, 20, 160, { length: 20, width: 20, thickness: 5 }),
];

const patioParts: Omit<Part, 'id'>[] = [
  part('tile', 'tile-natural', 'Patio slab', 0, 0, 4000, 3000, 1, { length: 4000, width: 3000, thickness: 20 }),
  part('substrate', 'underlay', 'Weed membrane', 0, 3100, 4000, 3000, 1, { length: 4000, width: 3000, thickness: 2 }),
  part('trim', 'movement', 'Movement joint', 0, 6200, 1000, 20, 14, { length: 1000, width: 20, thickness: 10 }),
  part('fix', 'spacer', 'Paving spacers', 0, 6300, 20, 20, 240, { length: 20, width: 20, thickness: 5 }),
  part('finish', 'sealer', 'Sealer', 60, 6300, 400, 300, 1, { length: 4000, width: 3000, thickness: 1 }),
];

const templates: Template[] = [
  { id: 'bathroom-floor', name: 'Bathroom floor', parts: bathroomFloorParts },
  { id: 'splashback', name: 'Kitchen splashback', parts: splashbackParts },
  { id: 'patio', name: 'Patio', parts: patioParts },
];

export const tiling: Profile = {
  id: 'tiling',
  name: 'Tiling',
  color: '#4a8c9e',
  displayUnit: 'mm',
  precision: 0,
  gridSize: 5,
  snap: true,
  materials,
  partKinds,
  templates,
};
