import type { Part, Profile, Template } from '../types';

const materials: Profile['materials'] = [
  {
    id: 'oak-25',
    name: 'Oak board 25 mm',
    category: 'hardwood',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 32.0,
    unitLabel: 'm',
    color: '#b07a45',
    stock: [{ length: 2400 }, { length: 4800 }],
    kerf: 3,
  },
  {
    id: 'walnut-20',
    name: 'Walnut board 20 mm',
    category: 'hardwood',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 45.0,
    unitLabel: 'm',
    color: '#6b4326',
    stock: [{ length: 2400 }, { length: 4800 }],
    kerf: 3,
  },
  {
    id: 'pine-18',
    name: 'Pine board 18 mm',
    category: 'softwood',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 8.0,
    unitLabel: 'm',
    color: '#d8b26a',
    stock: [{ length: 2400 }, { length: 4800 }],
    kerf: 3,
  },
  {
    id: 'cedar-20',
    name: 'Cedar board 20 mm',
    category: 'softwood',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 14.0,
    unitLabel: 'm',
    color: '#c08a55',
    stock: [{ length: 2400 }, { length: 4800 }],
    kerf: 3,
  },
  {
    id: 'ply-12',
    name: 'Birch plywood 12 mm',
    category: 'sheet',
    role: 'stock',
    measure: 'area' as const,
    costPerUnit: 38.0,
    unitLabel: 'm2',
    color: '#e3cfa5',
    stock: [{ length: 2440, width: 1220 }],
    kerf: 3,
  },
  {
    id: 'ply-18',
    name: 'Birch plywood 18 mm',
    category: 'sheet',
    role: 'stock',
    measure: 'area' as const,
    costPerUnit: 52.0,
    unitLabel: 'm2',
    color: '#ddc89a',
    stock: [{ length: 2440, width: 1220 }],
    kerf: 3,
  },
  {
    id: 'mdf-16',
    name: 'MDF 16 mm',
    category: 'sheet',
    role: 'stock',
    measure: 'area' as const,
    costPerUnit: 11.0,
    unitLabel: 'm2',
    color: '#d9cbb3',
    stock: [{ length: 2440, width: 1220 }],
    kerf: 3,
  },
  {
    id: 'veneer',
    name: 'Iron-on veneer',
    category: 'sheet',
    role: 'stock',
    measure: 'area' as const,
    costPerUnit: 16.0,
    unitLabel: 'm2',
    color: '#a9703f',
  },
  {
    id: 'dowel-10',
    name: 'Dowel 10 mm',
    category: 'joinery',
    role: 'stock',
    measure: 'linear' as const,
    costPerUnit: 1.2,
    unitLabel: 'm',
    color: '#c99f57',
  },
  {
    id: 'biscuit',
    name: 'Biscuit',
    category: 'joinery',
    role: 'stock',
    measure: 'count' as const,
    costPerUnit: 0.05,
    unitLabel: 'pc',
    color: '#d8c48f',
  },
  {
    id: 'hinge-35',
    name: 'Cabinet hinge 35 mm',
    category: 'hardware',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 2.4,
    unitLabel: 'pc',
    color: '#78808c',
  },
  {
    id: 'drawer-slide',
    name: 'Drawer slide pair',
    category: 'hardware',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 7.5,
    unitLabel: 'pair',
    color: '#8b95a1',
  },
  {
    id: 'handle',
    name: 'Handle',
    category: 'hardware',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 4.5,
    unitLabel: 'pc',
    color: '#c2a24a',
  },
  {
    id: 'screw-50',
    name: 'Wood screw 50 mm',
    category: 'fasteners',
    role: 'fixing',
    measure: 'count' as const,
    costPerUnit: 0.09,
    unitLabel: 'pc',
    color: '#9aa0aa',
  },
  {
    id: 'glue',
    name: 'Wood glue',
    category: 'finish',
    role: 'finish',
    measure: 'count' as const,
    costPerUnit: 6.0,
    unitLabel: 'bottle',
    color: '#d7d2c8',
  },
  {
    id: 'hardwax',
    name: 'Hard wax oil',
    category: 'finish',
    role: 'finish',
    measure: 'area' as const,
    costPerUnit: 9.5,
    unitLabel: 'm2',
    color: '#b7793f',
  },
];

const partKinds: Profile['partKinds'] = [
  {
    id: 'board',
    label: 'Board',
    defaultMaterialId: 'pine-18',
    defaultLength: 1200,
    defaultWidth: 140,
    defaultThickness: 18,
    defaultShape: 'line',
    measure: 'linear' as const,
  },
  {
    id: 'panel',
    label: 'Panel',
    defaultMaterialId: 'ply-12',
    defaultLength: 600,
    defaultWidth: 400,
    defaultThickness: 12,
    measure: 'area' as const,
  },
  {
    id: 'joinery',
    label: 'Joinery',
    defaultMaterialId: 'dowel-10',
    defaultLength: 300,
    defaultWidth: 10,
    defaultThickness: 10,
    defaultShape: 'line',
    measure: 'linear' as const,
  },
  {
    id: 'hardware',
    label: 'Hardware',
    defaultMaterialId: 'hinge-35',
    defaultLength: 60,
    defaultWidth: 60,
    defaultThickness: 20,
    defaultShape: 'circle',
    measure: 'count' as const,
  },
  {
    id: 'finish',
    label: 'Finish',
    defaultMaterialId: 'hardwax',
    defaultLength: 400,
    defaultWidth: 300,
    defaultThickness: 1,
    measure: 'area' as const,
  },
];

function part(
  kindId: string,
  materialId: string,
  label: string,
  x: number,
  y: number,
  sizeX: number,
  sizeY: number,
  quantity: number,
  dimensions: { length: number; width: number; thickness: number },
): Omit<Part, 'id'> {
  return {
    kindId,
    materialId,
    label,
    position: { x, y },
    size: { x: sizeX, y: sizeY },
    rotation: 0,
    quantity,
    dimensions,
  };
}

const shelfParts: Omit<Part, 'id'>[] = [
  part('board', 'oak-25', 'Shelf', 0, 0, 900, 200, 3, { length: 900, width: 200, thickness: 25 }),
  part('board', 'oak-25', 'Side', 0, 220, 800, 200, 2, { length: 800, width: 200, thickness: 25 }),
  part('board', 'pine-18', 'Back rail', 0, 440, 900, 60, 1, { length: 900, width: 60, thickness: 18 }),
  part('joinery', 'dowel-10', 'Dowel', 400, 440, 30, 10, 12, { length: 40, width: 10, thickness: 10 }),
  part('hardware', 'screw-50', 'Screws', 520, 440, 60, 60, 24, { length: 50, width: 5, thickness: 5 }),
  part('finish', 'hardwax', 'Hard wax oil', 620, 440, 400, 200, 1, { length: 900, width: 400, thickness: 1 }),
];

const workbenchParts: Omit<Part, 'id'>[] = [
  part('board', 'oak-25', 'Top slab', 0, 0, 1800, 300, 2, { length: 1800, width: 300, thickness: 45 }),
  part('board', 'pine-18', 'Apron', 0, 340, 1500, 100, 2, { length: 1500, width: 100, thickness: 25 }),
  part('board', 'pine-18', 'Leg', 0, 460, 90, 90, 4, { length: 850, width: 90, thickness: 90 }),
  part('board', 'pine-18', 'Lower stretcher', 0, 580, 1300, 90, 2, { length: 1300, width: 90, thickness: 45 }),
  part('joinery', 'biscuit', 'Biscuits', 0, 700, 30, 20, 16, { length: 30, width: 20, thickness: 4 }),
  part('hardware', 'screw-50', 'Screws', 120, 700, 60, 60, 40, { length: 50, width: 5, thickness: 5 }),
  part('finish', 'hardwax', 'Hard wax oil', 240, 700, 400, 300, 1, { length: 1900, width: 700, thickness: 1 }),
];

const cabinetParts: Omit<Part, 'id'>[] = [
  part('panel', 'ply-18', 'Carcass side', 0, 0, 720, 400, 2, { length: 720, width: 400, thickness: 18 }),
  part('panel', 'ply-18', 'Shelf', 0, 440, 680, 380, 2, { length: 680, width: 380, thickness: 18 }),
  part('panel', 'ply-18', 'Back panel', 0, 840, 680, 720, 1, { length: 680, width: 720, thickness: 12 }),
  part('board', 'oak-25', 'Door', 0, 1600, 700, 360, 1, { length: 700, width: 360, thickness: 25 }),
  part('hardware', 'hinge-35', 'Cabinet hinge', 700, 0, 60, 60, 2, { length: 60, width: 60, thickness: 20 }),
  part('hardware', 'handle', 'Handle', 700, 100, 160, 20, 1, { length: 160, width: 20, thickness: 12 }),
  part('hardware', 'drawer-slide', 'Drawer slide', 700, 200, 350, 45, 1, { length: 350, width: 45, thickness: 12 }),
  part('finish', 'hardwax', 'Hard wax oil', 700, 300, 400, 300, 1, { length: 1400, width: 1000, thickness: 1 }),
];

const templates: Template[] = [
  { id: 'shelf', name: 'Wall shelf', parts: shelfParts },
  { id: 'workbench', name: 'Workbench', parts: workbenchParts },
  { id: 'cabinet', name: 'Base cabinet', parts: cabinetParts },
];

export const woodworking: Profile = {
  id: 'woodworking',
  name: 'Woodworking',
  color: '#7a5c2e',
  displayUnit: 'mm',
  precision: 0,
  gridSize: 10,
  snap: true,
  materials,
  partKinds,
  templates,
};
